### ISSUE TITLE
Outdated add_block endpoint?

### ISSUE THREAD

**Issue by curranbriant** [frnsys/arena#2]
The Arena API docs seem outdated because sending a post request to  slug/blocks returns a 404 not found - ie https://api.are.na/v2/channels/aesthetics-iqxn6ahbe0u/blocks

It seems like `slug/contents` is where blocks are held now.  (https://api.are.na/v2/channels/aesthetics-iqxn6ahbe0u/contents)
I tried updating add_block to post to /slug/content but am getting error - `__init__() missing 1 required positional argument 'id'`. Im not sure exactly how to fix this, but if I find the new way to created new blocks then ill submit a pull request.  

Thanks for building this out! its been super helpful

**Comment by davidbenque** [comment]
Hi have you found a solution for this? trying to add a block with 
```
chan = arena.channels.channel('automation_tests')
block = chan.add_block(content="hello from Python")
```
gives me:
```
HTTPError: 404 Client Error: Not Found for url: https://api.are.na/v2/channels/automation_tests/blocks
```

**Comment by curranbriant** [comment]
@davidbenque yep, you have to send an authenticated request to access the `/blocks` endpoint to add a block.... I haven't actually tried it with this module but I verified that's how it works using the javascript API wrapper

**Comment by curranbriant** [comment]
https://dev.are.na/documentation/authentication

**Comment by davidbenque** [comment]
Thank you for the pointer. I thought I was authenticated with my personal token, but maybe that is where my problem is. I was able to retrieve all my channels, including private ones with the method below. Creating new blocks throws 404. 

```
from arena import Arena
import os

arena_token = os.environ['ARENA_TOKEN']
arena = Arena(arena_token)

chan = arena.channels.channel('automation_tests')
block = chan.add_block(content="hello from Python")
```

**Comment by curranbriant** [comment]
Thats where I was when I switched to another API wrapper.... were you able to find a way to make it work? @davidbenque

**Comment by davidbenque** [comment]
I haven't had any luck. I did check that I am correctly authenticated. I didn't try to fix the module code but using `requests` in the meantime:

```
import requests

url = "https://api.are.na/v2/channels/automation_tests/blocks"

block = {
    'access_token': os.environ['arena_token'],
    'source': 'https://website.com/image.png',
    'description': 'something about the image',
    'title': 'test image'
}

x = requests.post(url, data=block)
```

**Comment by absentees** [comment]
Was this solved? I'm having similar issues with the js client and the add/create block endpoint.
